version: "3.8"
services:
    php:
        container_name: php_test
        build:
            context: config/php
            dockerfile: Dockerfile
        working_dir: /test
        volumes:
            - ../:/test

    nginx:
        container_name: nginx_test
        image: nginx:alpine
        working_dir: /test
        volumes:
            - ../:/test
            - ./config/nginx/$DOCKER_ENV/default.conf:/etc/nginx/conf.d/default.conf
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"

    postgres:
        container_name: postgres_test
        image: postgres
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    redis:
        container_name: redis_test
        image: redis
